name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.0.app/Contents/Developer
      
      - name: Show Xcode version
        run: xcodebuild -version
        
      - name: Cache Xcode DerivedData
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-xcode-${{ hashFiles('**/*.xcodeproj') }}
          restore-keys: |
            ${{ runner.os }}-xcode-
      
      - name: Build and Test
        run: |
          xcodebuild \
            -project ttcd.xcodeproj \
            -scheme ttcd \
            -destination 'platform=macOS' \
            clean build test
      
      - name: Archive App
        if: github.ref == 'refs/heads/main'
        run: |
          xcodebuild \
            -project ttcd.xcodeproj \
            -scheme ttcd \
            -destination 'platform=macOS' \
            -archivePath build/ttcd.xcarchive \
            archive
      
      - name: Export App
        if: github.ref == 'refs/heads/main'
        run: |
          xcodebuild \
            -exportArchive \
            -archivePath build/ttcd.xcarchive \
            -exportPath build/ \
            -exportOptionsPlist ExportOptions.plist || \
          xcodebuild \
            -exportArchive \
            -archivePath build/ttcd.xcarchive \
            -exportPath build/ \
            -exportFormat app
      
      - name: Upload Build Artifacts
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: ttcd-app
          path: build/*.app
          retention-days: 30
